--- #YAML:1.0
###########################################################################
# $Id: META.yml,v 1.3 2003/09/27 18:12:53 wendigo Exp $
###########################################################################
#
# META.yml
#
# RCS Revision: $Revision: 1.3 $
# Date: $Date: 2003/09/27 18:12:53 $
#
# Copyright (C) 2003 Mark Rogaski, mrogaski@cpan.org; all rights reserved.
#
# See the README file included with the
# distribution for license information.
#
# http://module-build.sourceforge.net/META-spec.html
#
# $Log: META.yml,v $
# Revision 1.3  2003/09/27 18:12:53  wendigo
# Removed unecessary prerequsites.
#
#
###########################################################################

name:                   Log-Agent
version:                0.305
version_from:           Agent.pm
license:                artistic
distribution_type:      module
installdirs:            site
requires:               
    Tie::Array: 0
recommends:
    Callback: 0
build_requires:
    Test: 0
dynamic_config:         0

